version: 2
jobs:
  build:
    working_directory: ~/django-json-feed
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            py.test --junitxml=/tmp/test-results/python.xml
      - type: store_test_results
          path: /tmp/test-results
      - store_artifacts:
        path: /tmp/test-results
        destination: python
